// features/onboarding/models/onboarding_state.dart
// Purpose: Models representing stages, model registry, and progress for Kivo Workspace onboarding.

enum OnboardingStage {
  systemCheck,
  modelSelection,
  summary,
  downloading,
  installing,
  configurations,
  appearance,
  done,
}

class CuratedModel {
  final String id;
  final String name;
  final String category;
  final String capability;
  final String size;
  final double sizeGb;
  final String ram;
  final int ramGb;
  final String compatibility;
  final String description;

  const CuratedModel({
    required this.id,
    required this.name,
    required this.category,
    required this.capability,
    required this.size,
    required this.sizeGb,
    required this.ram,
    required this.ramGb,
    required this.compatibility,
    required this.description,
  });

  bool matchesSystemSpecs({required int systemRamGb, required bool hasHardwareAcceleration}) {
    if (systemRamGb < ramGb) return false;
    if (compatibility.contains('High-end') && !hasHardwareAcceleration) return false;
    return true;
  }
}

class OnboardingProgress {
  final OnboardingStage activeStage;
  final List<String> selectedModelIds;
  final double downloadSpeed; // MB/s
  final String downloadEta;
  final double downloadProgress; // 0.0 to 1.0
  final double downloadedMb;
  final double totalMb;
  final String? errorMessage;
  final bool isInternetConnected;
  final Map<String, String> systemSpecs;
  final Map<String, String> installStatus; // modelId/binary -> status string (e.g. "Downloading", "Completed")
  final bool isFfmpegInstalled;
  final bool isTesseractInstalled;
  final bool isPythonInstalled;
  final bool isEmbeddingModelInstalled;
  final List<String> installedOllamaModels;

  OnboardingProgress({
    this.activeStage = OnboardingStage.systemCheck,
    this.selectedModelIds = const ['qwen2.5:1.5b'],
    this.downloadSpeed = 0.0,
    this.downloadEta = 'Unknown',
    this.downloadProgress = 0.0,
    this.downloadedMb = 0.0,
    this.totalMb = 0.0,
    this.errorMessage,
    this.isInternetConnected = true,
    this.systemSpecs = const {},
    this.installStatus = const {},
    this.isFfmpegInstalled = false,
    this.isTesseractInstalled = false,
    this.isPythonInstalled = false,
    this.isEmbeddingModelInstalled = false,
    this.installedOllamaModels = const [],
  });

  OnboardingProgress copyWith({
    OnboardingStage? activeStage,
    List<String>? selectedModelIds,
    double? downloadSpeed,
    String? downloadEta,
    double? downloadProgress,
    double? downloadedMb,
    double? totalMb,
    String? errorMessage,
    bool? isInternetConnected,
    Map<String, String>? systemSpecs,
    Map<String, String>? installStatus,
    bool? isFfmpegInstalled,
    bool? isTesseractInstalled,
    bool? isPythonInstalled,
    bool? isEmbeddingModelInstalled,
    List<String>? installedOllamaModels,
  }) {
    return OnboardingProgress(
      activeStage: activeStage ?? this.activeStage,
      selectedModelIds: selectedModelIds ?? this.selectedModelIds,
      downloadSpeed: downloadSpeed ?? this.downloadSpeed,
      downloadEta: downloadEta ?? this.downloadEta,
      downloadProgress: downloadProgress ?? this.downloadProgress,
      downloadedMb: downloadedMb ?? this.downloadedMb,
      totalMb: totalMb ?? this.totalMb,
      errorMessage: errorMessage,
      isInternetConnected: isInternetConnected ?? this.isInternetConnected,
      systemSpecs: systemSpecs ?? this.systemSpecs,
      installStatus: installStatus ?? this.installStatus,
      isFfmpegInstalled: isFfmpegInstalled ?? this.isFfmpegInstalled,
      isTesseractInstalled: isTesseractInstalled ?? this.isTesseractInstalled,
      isPythonInstalled: isPythonInstalled ?? this.isPythonInstalled,
      isEmbeddingModelInstalled: isEmbeddingModelInstalled ?? this.isEmbeddingModelInstalled,
      installedOllamaModels: installedOllamaModels ?? this.installedOllamaModels,
    );
  }
}

// Curated Model Registry containing >= 4 models per category across 15 categories.
final List<CuratedModel> curatedModelRegistry = [
  // --- Reasoning & Logic ---
  const CuratedModel(
    id: 'deepseek-r1:1.5b',
    name: 'DeepSeek R1 1.5B',
    category: 'Reasoning & Logic',
    capability: 'Reasoning & Logic',
    size: '1.1 GB',
    sizeGb: 1.1,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Advanced reasoning and mathematical logic in a lightweight parameter footprint.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:8b',
    name: 'DeepSeek R1 8B',
    category: 'Reasoning & Logic',
    capability: 'Deep Reasoning',
    size: '4.9 GB',
    sizeGb: 4.9,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Implements reinforcement learning reasoning. Exceptional at math, logic, and coding QA.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:14b',
    name: 'DeepSeek R1 14B',
    category: 'Reasoning & Logic',
    capability: 'Expert Reasoning',
    size: '9.0 GB',
    sizeGb: 9.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end GPUs / M-Series Macs',
    description: 'High-intellect reasoning engine for complex synthesis and logical deep dives.',
  ),
  const CuratedModel(
    id: 'qwen2.5-math:7b',
    name: 'Qwen 2.5 Math 7B',
    category: 'Reasoning & Logic',
    capability: 'Mathematical Synthesis',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Specially trained for multi-step math problems, equations, and mathematical retrieval.',
  ),

  // --- General Chat & Assistant ---
  const CuratedModel(
    id: 'qwen2.5:1.5b',
    name: 'Qwen 2.5 1.5B (Default)',
    category: 'General Chat & Assistant',
    capability: 'Balanced Chat',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Fast, highly reliable conversational model. Excels at context-grounded retrieval QA.',
  ),
  const CuratedModel(
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B',
    category: 'General Chat & Assistant',
    capability: 'Conversational Quality',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Meta\'s highly capable small conversational assistant. Excellent vocabulary and flow.',
  ),
  const CuratedModel(
    id: 'gemma2:9b',
    name: 'Gemma 2 9B',
    category: 'General Chat & Assistant',
    capability: 'Instruction Following',
    size: '5.5 GB',
    sizeGb: 5.5,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'Google\'s high-capacity open model. Excellent structural comprehension and detail.',
  ),
  const CuratedModel(
    id: 'llama3.1:8b',
    name: 'Llama 3.1 8B',
    category: 'General Chat & Assistant',
    capability: 'Balanced Generalist',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Standard industry benchmark for 8B chat and general language tasks.',
  ),

  // --- Coding & Technical ---
  const CuratedModel(
    id: 'qwen2.5-coder:1.5b',
    name: 'Qwen 2.5 Coder 1.5B',
    category: 'Coding & Technical',
    capability: 'Fast Coding',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Optimized for code suggestions, autocomplete, and syntax assistance on lower-spec hardware.',
  ),
  const CuratedModel(
    id: 'qwen2.5-coder:7b',
    name: 'Qwen 2.5 Coder 7B',
    category: 'Coding & Technical',
    capability: 'Full Code Generation',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'State-of-the-art coding assistant. Comparable to much larger models in programming tests.',
  ),
  const CuratedModel(
    id: 'codellama:7b',
    name: 'CodeLlama 7B',
    category: 'Coding & Technical',
    capability: 'Coding Assistant',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Meta\'s specialized coder model. High accuracy on python, C++, and javascript.',
  ),
  const CuratedModel(
    id: 'codellama:13b',
    name: 'CodeLlama 13B',
    category: 'Coding & Technical',
    capability: 'Heavy Code Synthesis',
    size: '7.3 GB',
    sizeGb: 7.3,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'Larger coder capacity. Handles longer program context and complex software architecture.',
  ),

  // --- Creative & Narrative ---
  const CuratedModel(
    id: 'gemma2:2b',
    name: 'Gemma 2 2B',
    category: 'Creative & Narrative',
    capability: 'Creative Assistant',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '6 GB+',
    ramGb: 6,
    compatibility: 'All devices',
    description: 'Google\'s 2B model which punches far above its weight class in creative expression.',
  ),
  const CuratedModel(
    id: 'mistral:latest',
    name: 'Mistral 7B',
    category: 'Creative & Narrative',
    capability: 'Narrative Flow',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'A classic favorite for narrative prose, storytelling, and high-entropy text generation.',
  ),
  const CuratedModel(
    id: 'hermes3:8b',
    name: 'Hermes 3 8B',
    category: 'Creative & Narrative',
    capability: 'Unbound Creative Writing',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Nous Research flag model. Highly customizable, creative, and immersive narrative styling.',
  ),
  const CuratedModel(
    id: 'llama3:8b',
    name: 'Llama 3 8B Instruct',
    category: 'Creative & Narrative',
    capability: 'Expressive Style',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Immersive, highly expressive chatbot tuning of the Meta Llama 3 architecture.',
  ),

  // --- Educational & Information ---
  const CuratedModel(
    id: 'phi3:latest',
    name: 'Phi-3 3.8B',
    category: 'Educational & Information',
    capability: 'Logical Explanation',
    size: '2.2 GB',
    sizeGb: 2.2,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Microsoft\'s high-reasoning small model. Excellent for conceptual teaching and summaries.',
  ),
  const CuratedModel(
    id: 'orca-mini:3b',
    name: 'Orca Mini 3B',
    category: 'Educational & Information',
    capability: 'Fact Explanation',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '6 GB+',
    ramGb: 6,
    compatibility: 'All devices',
    description: 'Small conversational assistant optimized for factual accuracy and instruction following.',
  ),
  const CuratedModel(
    id: 'phi3:medium',
    name: 'Phi-3 Medium 14B',
    category: 'Educational & Information',
    capability: 'Deep Explanations',
    size: '7.9 GB',
    sizeGb: 7.9,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end devices',
    description: 'Larger Microsoft model with deep textbook-like logic. Great for multi-domain tutoring.',
  ),
  const CuratedModel(
    id: 'qwen2.5:3b',
    name: 'Qwen 2.5 3B',
    category: 'Educational & Information',
    capability: 'Fast Retrieval & Tutoring',
    size: '1.9 GB',
    sizeGb: 1.9,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Intermediate Qwen size. Combines reasoning capabilities with fast CPU speeds.',
  ),

  // --- Medical & Science ---
  const CuratedModel(
    id: 'medllama2:7b',
    name: 'MedLlama 2 7B',
    category: 'Medical & Science',
    capability: 'Clinical QA',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Llama 2 model fine-tuned on medical journals, clinical QA datasets, and terminologies.',
  ),
  const CuratedModel(
    id: 'meditron:7b',
    name: 'Meditron 7B',
    category: 'Medical & Science',
    capability: 'Medical Diagnostics Support',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'EPFL open-source medical model trained extensively on clinical practice guidelines.',
  ),
  const CuratedModel(
    id: 'biogpt:latest',
    name: 'BioGPT 1.5B',
    category: 'Medical & Science',
    capability: 'Biological Extraction',
    size: '1.2 GB',
    sizeGb: 1.2,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Trained on PubMed literature. Exceptional at biomedical name extraction and science QA.',
  ),
  const CuratedModel(
    id: 'clinical-llama2:latest',
    name: 'Clinical-Llama 2 7B',
    category: 'Medical & Science',
    capability: 'Clinical Summaries',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Optimized for parsing doctor notes, clinical charts, and medical document summaries.',
  ),

  // --- Multilingual & Translation ---
  const CuratedModel(
    id: 'aya:8b',
    name: 'Aya 23 8B',
    category: 'Multilingual & Translation',
    capability: 'Multilingual Translation',
    size: '4.8 GB',
    sizeGb: 4.8,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Cohere\'s flagship multilingual model covering 23 different languages with high accuracy.',
  ),
  const CuratedModel(
    id: 'command-r:latest',
    name: 'Command R 35B',
    category: 'Multilingual & Translation',
    capability: 'Expert Localization',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'Super-High/Workstation specs',
    description: 'Large-scale multilingual model. Excels at enterprise-level localization and translation.',
  ),
  const CuratedModel(
    id: 'qwen2.5:7b',
    name: 'Qwen 2.5 7B',
    category: 'Multilingual & Translation',
    capability: 'Global Languages',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Outstanding performance across Asian, European, and Middle Eastern languages.',
  ),
  const CuratedModel(
    id: 'llama3.2:1b',
    name: 'Llama 3.2 1B (Multilingual)',
    category: 'Multilingual & Translation',
    capability: 'Fast Translation',
    size: '1.3 GB',
    sizeGb: 1.3,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Lightweight translator model for rapid localized text processing on CPU.',
  ),

  // --- Speed & Low-Resource ---
  const CuratedModel(
    id: 'qwen2.5:0.5b',
    name: 'Qwen 2.5 0.5B',
    category: 'Speed & Low-Resource',
    capability: 'Ultra-lightweight',
    size: '390 MB',
    sizeGb: 0.39,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Smallest Qwen model. Near-instantaneous response times, ideal for micro-servers.',
  ),
  const CuratedModel(
    id: 'tinyllama:latest',
    name: 'TinyLlama 1.1B',
    category: 'Speed & Low-Resource',
    capability: 'Fast CPU Chat',
    size: '637 MB',
    sizeGb: 0.63,
    ram: '2 GB+',
    ramGb: 2,
    compatibility: 'All devices',
    description: 'Compact 1B parameter model optimized for speed and local CPU inference.',
  ),
  const CuratedModel(
    id: 'llama3.2:1b',
    name: 'Llama 3.2 1B',
    category: 'Speed & Low-Resource',
    capability: 'Lightweight Assistant',
    size: '1.3 GB',
    sizeGb: 1.3,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Meta\'s smallest Llama model. Extremely responsive on basic office laptops.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:1.5b',
    name: 'DeepSeek R1 1.5B (Speed)',
    category: 'Speed & Low-Resource',
    capability: 'Fast Reasoning',
    size: '1.1 GB',
    sizeGb: 1.1,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Fastest reasoning model available. Ideal for running reasoning tasks on CPU.',
  ),

  // --- High-Capacity Reasoners ---
  const CuratedModel(
    id: 'deepseek-r1:14b',
    name: 'DeepSeek R1 14B (High)',
    category: 'High-Capacity Reasoners',
    capability: 'Complex Reasoning',
    size: '9.0 GB',
    sizeGb: 9.0,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end GPUs / Macs',
    description: 'Large-scale reasoning model. Capable of coding complex projects and proving math theorems.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:32b',
    name: 'DeepSeek R1 32B',
    category: 'High-Capacity Reasoners',
    capability: 'Super reasoning',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'High-end workstation GPU / Mac Studio',
    description: 'Professional reasoning capacity for multi-document comparisons and logic audits.',
  ),
  const CuratedModel(
    id: 'deepseek-r1:70b',
    name: 'DeepSeek R1 70B',
    category: 'High-Capacity Reasoners',
    capability: 'Extreme Reasoning',
    size: '42.0 GB',
    sizeGb: 42.0,
    ram: '96 GB+',
    ramGb: 96,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'State-of-the-art open reasoning model. Bypasses GPT-4o in mathematical benchmarks.',
  ),
  const CuratedModel(
    id: 'qwen2.5:72b',
    name: 'Qwen 2.5 72B',
    category: 'High-Capacity Reasoners',
    capability: 'Full Generalist Intelligence',
    size: '47.0 GB',
    sizeGb: 47.0,
    ram: '96 GB+',
    ramGb: 96,
    compatibility: 'Server GPUs / 128GB Unified RAM',
    description: 'Flagship Qwen model. Extreme knowledge density across coding, science, and languages.',
  ),

  // --- Agentic & Tool-Use ---
  const CuratedModel(
    id: 'llama3-groq-tool-use:8b',
    name: 'Llama 3 Groq Tool Use 8B',
    category: 'Agentic & Tool-Use',
    capability: 'JSON & Tool Calling',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Groq-optimized Llama 3 model designed specifically to output clean JSON schemas and arguments.',
  ),
  const CuratedModel(
    id: 'hermes3:8b',
    name: 'Hermes 3 8B (Agentic)',
    category: 'Agentic & Tool-Use',
    capability: 'Autonomous Executions',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Nous Research agent tuning. Highly skilled at tool utilization and multi-turn workflows.',
  ),
  const CuratedModel(
    id: 'qwen2.5:7b',
    name: 'Qwen 2.5 7B (Agentic)',
    category: 'Agentic & Tool-Use',
    capability: 'Function Orchestration',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Outstanding functional execution capabilities for agent loops.',
  ),
  const CuratedModel(
    id: 'command-r:latest',
    name: 'Command R 35B (Agent)',
    category: 'Agentic & Tool-Use',
    capability: 'Multi-step agent loops',
    size: '20.0 GB',
    sizeGb: 20.0,
    ram: '48 GB+',
    ramGb: 48,
    compatibility: 'Super-High/Workstation specs',
    description: 'Enterprise-grade agent executor. Native tool calling and multi-step workflow logic.',
  ),

  // --- Roleplay & Storytelling ---
  const CuratedModel(
    id: 'mythomax:latest',
    name: 'MythoMax 13B',
    category: 'Roleplay & Storytelling',
    capability: 'Immersive Prose',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'A custom merge of Llama models optimized for roleplay, dialogue, and creative stories.',
  ),
  const CuratedModel(
    id: 'hermes3:8b',
    name: 'Hermes 3 8B (Dialogue)',
    category: 'Roleplay & Storytelling',
    capability: 'Character Immersion',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: ' Nous Hermes dialouge tuning. Natural flow, great context preservation, and formatting.',
  ),
  const CuratedModel(
    id: 'mistral:latest',
    name: 'Mistral 7B (Narrative)',
    category: 'Roleplay & Storytelling',
    capability: 'Character Dialogue',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Classic favorite for generating rich prose and dynamic dialogue structures.',
  ),
  const CuratedModel(
    id: 'llama3:8b',
    name: 'Llama 3 8B (Instruct Roleplay)',
    category: 'Roleplay & Storytelling',
    capability: 'Interactive Conversations',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Highly adaptive and descriptive conversation agent for custom scenarios.',
  ),

  // --- Summarization ---
  const CuratedModel(
    id: 'phi3:medium',
    name: 'Phi-3 Medium 14B (Summary)',
    category: 'Summarization',
    capability: 'Long-text Summarization',
    size: '7.9 GB',
    sizeGb: 7.9,
    ram: '24 GB+',
    ramGb: 24,
    compatibility: 'High-end devices',
    description: '14B parameters with a massive context window. Ideal for summarizing long research articles.',
  ),
  const CuratedModel(
    id: 'qwen2.5:1.5b',
    name: 'Qwen 2.5 1.5B (Bullet Summary)',
    category: 'Summarization',
    capability: 'Rapid Bullet Points',
    size: '980 MB',
    sizeGb: 0.98,
    ram: '4 GB+',
    ramGb: 4,
    compatibility: 'All devices',
    description: 'Extremely fast. Excellent for generating key capsule notes from workspace files.',
  ),
  const CuratedModel(
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B (Executive summary)',
    category: 'Summarization',
    capability: 'Executive Summaries',
    size: '2.0 GB',
    sizeGb: 2.0,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Balanced assistant. Creates structured summaries, key takeaways, and quizzes.',
  ),
  const CuratedModel(
    id: 'gemma2:9b',
    name: 'Gemma 2 9B (Deep Synthesis)',
    category: 'Summarization',
    capability: 'Multi-document Synthesis',
    size: '5.5 GB',
    sizeGb: 5.5,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'Google\'s 9B model. Synthesizes concepts across multiple unrelated workspace files.',
  ),

  // --- Custom (Ollama tag loader) ---
  const CuratedModel(
    id: 'mistral:7b',
    name: 'Mistral 7B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'User defined',
    description: 'Pulls the standard 7B Mistral model from the Ollama library.',
  ),
  const CuratedModel(
    id: 'codegemma:2b',
    name: 'CodeGemma 2B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '1.6 GB',
    sizeGb: 1.6,
    ram: '6 GB+',
    ramGb: 6,
    compatibility: 'User defined',
    description: 'Pulls the lightweight coding model by Google from the Ollama library.',
  ),
  const CuratedModel(
    id: 'stable-beluga:7b',
    name: 'Stable Beluga 7B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '3.8 GB',
    sizeGb: 3.8,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'User defined',
    description: 'Pulls Stability AI\'s fine-tuned assistant from the Ollama library.',
  ),
  const CuratedModel(
    id: 'llama2:13b',
    name: 'Llama 2 13B (Custom)',
    category: 'Custom',
    capability: 'Ollama Tag Sync',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'User defined',
    description: 'Pulls Meta\'s classic 13B Llama 2 model from the Ollama library.',
  ),

  // --- Uncensored ---
  const CuratedModel(
    id: 'dolphin-mistral:latest',
    name: 'Dolphin Mistral 7B',
    category: 'Uncensored',
    capability: 'Uncensored General Assistant',
    size: '4.1 GB',
    sizeGb: 4.1,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'Mid-end devices',
    description: 'Mistral 7B tuned by Eric Hartford. Standard uncensored assistant, highly direct.',
  ),
  const CuratedModel(
    id: 'dolphin-llama3:8b',
    name: 'Dolphin Llama 3 8B',
    category: 'Uncensored',
    capability: 'Uncensored Llama Assistant',
    size: '4.7 GB',
    sizeGb: 4.7,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'Mid-to-High end devices',
    description: 'Llama 3 8B uncensored. High conversational density without alignment filters.',
  ),
  const CuratedModel(
    id: 'wizard-vicuna-uncensored:13b',
    name: 'Wizard Vicuna 13B Uncensored',
    category: 'Uncensored',
    capability: 'Uncensored Complex QA',
    size: '7.4 GB',
    sizeGb: 7.4,
    ram: '16 GB+',
    ramGb: 16,
    compatibility: 'High-end devices',
    description: 'A classic large uncensored model. Good for detailed queries in unfiltered domains.',
  ),
  const CuratedModel(
    id: 'dolphin-phi3:latest',
    name: 'Dolphin Phi-3 3.8B',
    category: 'Uncensored',
    capability: 'Uncensored Logical Assistant',
    size: '2.2 GB',
    sizeGb: 2.2,
    ram: '8 GB+',
    ramGb: 8,
    compatibility: 'All devices',
    description: 'Uncensored variant of Microsoft\'s Phi-3 model. Strong logic in a small package.',
  ),
];
